baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-redlounge"

[params]
sidebartitle = "My Site"
sidebartagline = "Is super awesome"
# sidebarphoto = "/img/photo.png"

[[menu.main]]
name = "Blog"
url = "/posts"
[[menu.main]]
name = "Profile"
url = "/profile"

[[menu.footer]]
name = "Blog"
url = "/posts"
[[menu.footer]]
name = "Profile"
url = "/profile"
